---
title: "Proyecto"
author: "Daniel Sabater"
date: '2022-06-05'
output: html_document
---

```{r setup, include=FALSE}
# Programacion hecha por Joshua Cervantes, Moisés Monge y Daniel Sabater
# Se cargan los paquetes
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
library(lifecontingencies)
library(tidyverse)
library(lubridate)
library(readxl)
library(kableExtra)
library(xtable)
library(stringr)
library(magrittr) # uso de %<>% con funciones de dplyr
# library(xts)
# library(tinytex)


# Se cargan las bases de datos

Afiliados_31_12_2021 <- read_excel("Planilla_Compañia_31_12_2021.xlsx")
Pensionados_31_12_2021 <- read_excel("Compañia_Pensionados_31_12_2021.xlsx", range = "A1:F5006")


# Tablas de decrementos

TablasDecrementosHombres <- read_excel("Tablas de decrementos.xlsx",
  sheet = "Hombres")
TablasDecrementosMujeres <- read_excel("Tablas de decrementos.xlsx",
  sheet = "Mujeres")

# Tablas de mortalidad dinámicas

TablaDinamica_lxsHombres <- as.data.frame(read_excel("TablaDinamica-lxs.xls",
  sheet = "Hombres"))
TablaDinamica_lxsMujeres <- as.data.frame(read_excel("TablaDinamica-lxs.xls",
  sheet = "Mujeres"))

# Se genera lista con las tablas actuariales de los hombres

ListaDeTablasHombres <- list()
for (j in 1:(length(TablaDinamica_lxsHombres) - 1)) {
  ListaDeTablasHombres[[j]] <- with(
    TablaDinamica_lxsHombres,
    new(
      "actuarialtable",
      interest = 0.06,
      x = TablaDinamica_lxsHombres[, 1],
      lx = TablaDinamica_lxsHombres[, j + 1],
      name = paste("E", (j - 1), sep = "")
    )
  )
}

names(ListaDeTablasHombres) <- paste("E", seq(0, 115), sep = "")

# Se genera lista con las tablas actuariales de las mujeres

ListaDeTablasMujeres <- list()
for (j in 1:(length(TablaDinamica_lxsMujeres) - 1)) {
  ListaDeTablasMujeres[[j]] <- with(
    TablaDinamica_lxsMujeres,
    new(
      "actuarialtable",
      interest = 0.06,
      x = TablaDinamica_lxsMujeres[, 1],
      lx = TablaDinamica_lxsMujeres[, j + 1],
      name = paste("E", (j - 1), sep = "")
    )
  )
}

names(ListaDeTablasMujeres) <- paste("E", seq(0, 115), sep = "")

# Se establece la echa de la evaluación

dia_de_evaluacion <- as.Date("31/12/2021", format = "%d/%m/%Y")

# Afiliados

# Cálculo de edades afiliados

edad <- floor(time_length(difftime(
  dia_de_evaluacion,
  as.Date(as.POSIXct(Afiliados_31_12_2021$Fecha_nacimiento), "UTC")
), "years"))

# Depuración de la columna 'Fecha_ingreso'

Afiliados_31_12_2021 %<>% mutate(Fecha_ingreso = paste(substr(Fecha_ingreso, 1, 4),
  "/", substr(Fecha_ingreso, 5, 6), "/", substr(Fecha_ingreso, 7, 8),
  sep = ""
))

# Depuración de la columna 'Fecha_nacimiento'

Afiliados_31_12_2021 %<>% mutate(Fecha_nacimiento = format(Fecha_nacimiento, "%Y/%m/%d"))

# Cálculo de antigüedad

antiguedad <- time_length(difftime(
  dia_de_evaluacion,
  as.Date(
    Afiliados_31_12_2021$Fecha_ingreso,
    "%Y/%m/%d"
  )
), "years")

# Inclusión de las variables de edad y antigüedad en la base de datos

Afiliados_31_12_2021 %<>% mutate("Edad" = edad, "Antiguedad" = antiguedad)

# Se calcula edad de los pensionados

Pensionados_31_12_2021 %<>% mutate(FEC_NAC = paste(substr(FEC_NAC, 1, 4),
  "/", substr(FEC_NAC, 5, 6), "/", substr(FEC_NAC, 7, 8),
  sep = ""
))

Pensionados_31_12_2021 %<>% mutate(FEC_RIG_PEN = paste(substr(FEC_RIG_PEN, 1, 4),
  "/", substr(FEC_RIG_PEN, 5, 6), "/", substr(FEC_RIG_PEN, 7, 8),
  sep = ""
))

edad <- floor(time_length(
  difftime(
    dia_de_evaluacion,
    as.Date(
      Pensionados_31_12_2021$FEC_NAC,
      "%Y/%m/%d"
    )
  ),
  "years"
))

tiempo_pension <- floor(time_length(
  difftime(
    dia_de_evaluacion,
    as.Date(
      Pensionados_31_12_2021$FEC_RIG_PEN,
      "%Y/%m/%d"
    )
  ),
  "years"
))

Pensionados_31_12_2021 %<>% mutate("Edad" = edad, "T_Pension" = tiempo_pension)

# se crean bases de datos según genero

afil_hombres <- Afiliados_31_12_2021 %>% filter(Sexo == "M")
pen_hombres <- Pensionados_31_12_2021 %>% filter(SEX == "M")
afil_mujeres <- Afiliados_31_12_2021 %>% filter(Sexo == "F")
pen_mujeres <- Pensionados_31_12_2021 %>% filter(SEX == "F")
```

## Tablas de multiples decrementos


```{r}

ProMuerte <- function(q1,q2,q3,q4) {
  a<-q1*((-3*q2*q3*q4)/12+4*(q2*q3+q3*q4+q4*q2)/12-6*(q2+q3+q4)/12+1)
  b<-q2*((-3*q1*q3*q4)/12+4*(q1*q3+q3*q4+q4*q1)/12-6*(q1+q3+q4)/12+1)
  c<-q3*((-3*q2*q1*q4)/12+4*(q2*q1+q1*q4+q4*q2)/12-6*(q2+q1+q4)/12+1)
  d<-q4*((-3*q2*q3*q1)/12+4*(q2*q3+q3*q1+q1*q2)/12-6*(q2+q3+q1)/12+1)
  qx<-(a+b+c+d)
  
  return(data.frame("qx1"=a,"qx2"=b,"qx3"=c,"qx4"=d,"qxC"=qx))
}

# Se genera lista con las tablas de multiples decrementos de los hombres
MDListaDeTablasHombres <- list()
for (m in 1:116) {

qxs<-ProMuerte(TablasDecrementosHombres$Invalidez,TablasDecrementosHombres$Jubilacion,TablasDecrementosHombres$Retiro, qxt(ListaDeTablasHombres[[m]],0,c(1:116)))

Tabladevida<- as.data.frame(qxs)

Tabladevida$lx<-(1000000:(1000000-115))

for (i in 1:115) {
  Tabladevida$lx[i+1]<-Tabladevida$lx[i]-Tabladevida$lx[i]*Tabladevida$qxC[i]
}

Tabladevida$d1<-Tabladevida$lx*Tabladevida$qx1
Tabladevida$d2<-Tabladevida$lx*Tabladevida$qx2
Tabladevida$d3<-Tabladevida$lx*Tabladevida$qx3
Tabladevida$d4<-Tabladevida$lx*Tabladevida$qx4

Tabladevida$d4[1]+Tabladevida$lx[2]

MDListaDeTablasHombres[[m]] <- 
  new(
    "mdt",
    table = Tabladevida[,7:10],
    name = paste("E", (m - 1), sep = "")
  )

}

names(MDListaDeTablasHombres) <- paste("E", seq(0, 115), sep = "")





# Se genera lista con las tablas de multiples decrementos de las mujeres

MDListaDeTablasMujeres <- list()
for (m in 1:116) {
qxs<-ProMuerte(TablasDecrementosMujeres$Invalidez,TablasDecrementosMujeres$Jubilacion,TablasDecrementosMujeres$Retiro, qxt(ListaDeTablasMujeres[[m]],0,c(1:116)))

Tabladevida<- as.data.frame(qxs)

Tabladevida$lx<-(1000000:(1000000-115))

for (i in 1:115) {
  Tabladevida$lx[i+1]<-Tabladevida$lx[i]-Tabladevida$lx[i]*Tabladevida$qxC[i]
}

Tabladevida$d1<-Tabladevida$lx*Tabladevida$qx1
Tabladevida$d2<-Tabladevida$lx*Tabladevida$qx2
Tabladevida$d3<-Tabladevida$lx*Tabladevida$qx3
Tabladevida$d4<-Tabladevida$lx*Tabladevida$qx4

Tabladevida$d4[1]+Tabladevida$lx[2]

MDListaDeTablasMujeres[[m]] <-
  new(
    "mdt",
    table = Tabladevida[,7:10],
    name = paste("E", (m - 1), sep = "")
  )
}

names(MDListaDeTablasMujeres) <- paste("E", seq(0, 115), sep = "")

rm(qxs)


```












## Escala salarial
```{r}

```






# Estadistica
```{r}
# Ejemplo esperanza de vida
Edad <- 30
exn(ListaDeTablasHombres[[Edad + 1]], x = Edad, type = "curtate")
```



# Estocástico

```{r}
# Funcion para pensiones herededas
pension_heredada <- function(edad, monto, activo, tasa_descuento, m, inflacion, v) {
  Edad <- edad
  suma <- 0
  simulacion <- simulaciones
  ajuste <- 1
  j <- 1 / m
  i <- 1
  # Se verifica que la persona no haya tenido el beneficio mas de 10 anhos
  if (activo < 10) {
    tiempo_restante <- c(0:activo - 1)
    v_n <- v^(tiempo_restante) # Para traer en cada anhos
    a_m <- (1 + tasa_descuento)^(1 / m) * (1 - v) / (m * ((1 + tasa_descuento)^(1 / m) - 1)) * v_n
    suma <- suma + simulaciones * sum(a_m)
    if (sex) {
      probabilidad <- pxt(ListaDeTablasHombres[[(Edad + 1)]], x = edad, t = 10 - activo)
    } else {
      probabilidad <- pxt(ListaDeTablasMujeres[[(Edad + 1)]], x = edad, t = 10 - activo)
    }
    vivos <- sum(rbinom(n = simulacion, size = 1, prob = probabilidad))
    simulacion <- vivos
    edad <- edad + 10 - activo
    suma <- suma + v^j * ajuste * vivos
    ajuste <- ajuste * (1 + inflacion)^(10 - activo)
    j <- 10
  }
  while (simulacion > 0) {
    if (sex) {
      probabilidad <- pxt(ListaDeTablasHombres[[(Edad + 1)]], x = edad, t = 1 / m)
    } else {
      probabilidad <- pxt(ListaDeTablasMujeres[[(Edad + 1)]], x = edad, t = 1 / m)
    }
    vivos <- sum(rbinom(n = simulacion, size = 1, prob = probabilidad))
    simulacion <- vivos
    edad <- edad + 1 / m
    suma <- suma + v^j * ajuste * vivos * 2^(i == 12)
    ajuste <- ajuste * (1 + inflacion)^(i == 12)
    j <- j + 1 / m
    i <- (1 + i) * (i < 12) + 1 * (i == 12)
  }
  return(monto * suma / simulaciones)
}

pension_propia <- function(edad, monto, t_descuento, m, simulaciones, v, inflacion) {
  Edad <- edad
  suma <- 0
  simulacion <- simulaciones
  ajuste <- Afiliados_31_12_2021
}

pension_pen <- function(base_de_datos, sex, t_descuento, m, simulaciones) {
  v <- 1 / (1 + t_descuento)
  edades <- base_de_datos$Edad
  tiempo_activo <- base_de_datos$T_Pension
  antiguedades <- 0
  montos <- base_de_datos$MON_PENSION
  fn2 <- function(edad, monto, activo) {
    Edad <- edad
    suma <- 0
    simulacion <- simulaciones
    # monto<-monto*(v*aumento)^(max(jubilacion-Edad,0)) en este caso si se descomenta se calcula para los ya pensionados
    # monto<-monto
    ajuste <- 1
    j <- 1 / m
    i <- 1
    while (simulacion > 0) {
      if (sex) {
        probabilidad <- pxt(ListaDeTablasHombres[[(Edad + 1)]], x = edad, t = 1 / m)
      } else {
        probabilidad <- pxt(ListaDeTablasMujeres[[(Edad + 1)]], x = edad, t = 1 / m)
      }
      vivos <- sum(rbinom(n = simulacion, size = 1, prob = probabilidad))
      simulacion <- vivos
      edad <- edad + 1 / m
      suma <- suma + v^j * ajuste * vivos
      ajuste <- ajuste * (1 + inflacion)^(i == 12)
      j <- j + 1 / m
      i <- (1 + i) * (i < 12) + 1 * (i == 12)
    }
    return(monto * suma / simulaciones)
  }
  valores <- mapply(FUN = fn2, edad = edades, monto = montos, anti = antiguedades)
  return(sum(valores))
}
```



# Deterministico



# Funciones que nos sirven a ambos

```{r}
#porcentaje de pensión
porcentaje_de_pension <- function(antiguedad) {
  porcebtajeVejez<-c( (antiguedad >= 5  & antiguedad < 10) * 0.10 +
                      (antiguedad >= 10 & antiguedad < 15) * 0.15 +
                      (antiguedad >= 15 & antiguedad < 20) * 0.20 +
                      (antiguedad >= 20 & antiguedad < 25) * 0.25 +
                      (antiguedad >= 25 & antiguedad < 30) * 0.30 +
                      (antiguedad >= 30 & antiguedad < 35) * 0.35 +
                      (antiguedad >= 35) * 0.4
                    )
  return(porcebtajeVejez)
}


RebajoFondosInsuficientes <- function(MontodePension) {
  MontoRebajado<-c( 
     MontodePension*0.10+
    (MontodePension >= 2293400 ) * 0.35 * MontodePension+
    (MontodePension >= 2866750 ) * 0.45 * MontodePension+
    (MontodePension >= 3583437.50) * 0.55 * MontodePension+
    (MontodePension >= 4479296.88) * 0.65 *MontodePension
  )
  if (MontoRebajado>MontodePension*0.55) {
    return(MontodePension*0.55)
  }
  return(MontoRebajado)
}
```

## Personal activo


```{r}

```


## Personas ya pensionadas
```{r}

#Calculo de los q





```








